# frozen_string_literal: true

class TbTask < ActiveRecord::Base
  # main config ...............................................................
  audited
  self.table_name = :tb_tasks

  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :tb_items, class_name: 'TbItem', foreign_key: :tb_tasks_id
  accepts_nested_attributes_for :tb_items, reject_if: :all_blank, allow_destroy: true

  # validations ...............................................................
  validates_presence_of :title
  validates_length_of :title, maximum: 255

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def tb_items_build
    return tb_items.build if tb_items.blank?
    tb_items
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
